### PR TITLE
Full Rewrite in ES6 and removal of PHP

### PR DESCRIPTION
**Pull request by apmatthews**
Currently, cdn.ncsu.edu has to be run from a server that supports PHP because of the utility bar. In order to remove this requirement and get a step closer to a true CDN, we had to figure out a way to remove PHP without breaking existing implementations. The solution implemented here has 2 parts:

1. Use mod_rewrite to serve ub-php.js whenever ub.php is requested.
2. Find the requesting `<script>` tag in the DOM and extract configs from the query string.

From there, we can initialize the utility bar however we choose.

Since we are shifting to a full JS implementation of the bar, I thought it would be a good opportunity to refactor things. The main improvements here:

- Removed the Compass library dependency.
- Introduced [Laravel Mix](https://github.com/JeffreyWay/laravel-mix) for builds.
- Removed the need to compile a separate stylesheet for each color option.
- The bar now injects all CSS into `<style>` block rather than making a separate stylesheet request.
- Moved HTML markup to a `template.html` that is imported and minified through the webpack build. Improves maintainability.
- Use of ES6 features. (This is my first attempt at using ES6, so if I'm "not doing it right" please let me know)
- Improved readability.
- Improved validation and security.

If merged, this should address #3, #4, and #5. The names are fairly generic things that could always be improved, but I think this addresses their original intentions.

As for performance, using this version of the bar will take us from about 30kb of data served over 4 HTTP requests to about 40kb of data served over 2 requests. I suspect the bar will be noticeably faster.

The rewrite also sets us up for easier testing. With the removal of hard coded cdn.ncsu.edu references, local testing is already much easier from `demo.php`. Eventually, I'd like to introduce a testing process that could run during builds (something like [ava](https://github.com/avajs/ava)?). I'd also like to look at building `main.js` into `ub-php.js` in whatever way makes the most sense. That would get us down to a single HTTP request.

If anyone wants to see it in action, I've got it running on [brand.ncsu.edu](https://brand.ncsu.edu/). You can run this version from cdn.ncsu.edu by using the following (same [query string params](https://brand.ncsu.edu/downloads/) as ub.php of course):

`<script src="https://cdn.ncsu.edu/brand-assets/utility-bar/ub-php.js"></script>`

Lastly, I'll add a README.md to this PR with the this info, but here's how you build:

- Pull the branch
- `npm install`
- `npm run dev` for local development and testing. You can also `npm run watch`.
- `npm run production` builds the minified `dist` package.

Would love to get some feedback before merging. Looking at you @jrchamp 👀

### CODE REVIEW

**Comment by jrchamp** [comment]
Loving the simplified setup! Maybe we can get down to 1 JS file?

Need to step away, but I wanted to note a couple items I've seen so far:

- https://github.com/ncstate/utility-bar/blob/full-rewrite/src/main.js#L24 Might want to add a space before is-hidden so it won't combine that class with one that's already there.
- placeholder text that contains spaces in the URL triggers "Illegal character in query: space is not allowed.", so a user needs to use %20, but that is rendered as a literal and not URL decoded.
- placeholder text allows HTML injection, which may result in a XSS vulnerability (not sure if googlecustomcode has same issue)

**Comment by apmatthews** [comment]
Thanks! I'll look over those things and make some updates. Let me know if you find anything else.

**Comment by apmatthews** [comment]
c2313f6 should address the items raised so far. To elaborate:

- Looks like the `is-hidden` class toggle is working properly as-is. The class is present on page load and already has a space in front of it. That space remains throughout the process of toggling `is-hidden`.
- Added URL decoding to the placeholder including "+" for spaces, which is what the brand site suggests using.
- Placeholder and googleCustomSearch options will be reset to default if they contain the following characters `&` `"` `<` `'` `>` `` ` ``. I couldn't find a straight answer on the best way to filter input in these contexts, so this is what I came up with. I think it's safe, but please let me know if I've overlooked something.

**Comment by jrchamp** [comment]
More successes:
- compatible with both `&` and W3C compliant `&amp;` 
- compatible with strict-dynamic Content-Security-Policy
- really liking the input validation for color, showBrick and maxWidth (1e3 works, which was a fun surprise)

Additional notes:
- The googleCustomSearchCode is slightly more strict than the placeholder text (appears to be truncating the string when it finds a `>` that occurs outside of a quoted string), but still allows for HTML attribute injection. 
- The font color for the "minor" links is "999", a gray that does not meet accessibility requirements at the 14px font size. The least-white gray in the brand guidelines that meets the requirements on a Reynolds Red background is "ccc" (25% Gray).
- The background color for the links section in the gray theme is "1a1a1a", which does not appear to be part of the brand or the tints (at least not a document that I have). Perhaps use black "000"?

**Comment by jrchamp** [comment]
Comments after testing with c2313f6:
The option filtering for placeholder and google is successfully defeating my attempts! Documentation about this would help because it drops the values silently, which may be an issue for users who have ampersands in their organization/department. Another way to filter the input would be to replace the target characters with the empty string, stripping out only the offending characters. Conversely, whitelisting allowed characters (letters, numbers and spaces) and removing non-allowed characters would likely be the safest, but most restrictive solution, example: options.placeholder = options.placeholder.replace(/[^a-zA-Z0-9 ]/g, '');

**Comment by apmatthews** [comment]
I'm planning to follow up on the color stuff with a designer, but should have an update on that soon. Meanwhile, I revisited the placeholder and custom search validation in 896dcf7. I decided to allow ampersands but strip the remaining illegal characters. I didn't want to be as restrictive as a whitelist.

**Comment by jrchamp** [comment]
Sounds good. Here's the a tool I was using for checking the color contrast accessibility: https://accessibility.oit.ncsu.edu/tools/color-contrast/accessible-color-palette.php?&colors=ffffff,f2f2f2,cccccc,666666,333333,000000,990000,999999,1a1a1a&main=333333&level=AA

The red theme is all set now. The black theme uses 333333 (20% lighten) for the link section background which fails with the 999999 link text. The gray theme uses 1a1a1a (10% darken) as the link section background which passes with the 999999 link text.

**Comment by apmatthews** [comment]
Pushed some color changes yesterday that I think wrap this up. It fixes the accessibility issues.

The colors that aren't brand-official will be fine for now. Since utility bar was developed while the brand was still being defined, we ended up with some deviations from the final colors. Bootstrap had the same problem. We're planning to start looking at branding Bootstrap 4 soon, at which point we will make color adjustments as needed.

 I'm planning to merge and deploy today. Thanks for all the feedback!

**Comment by jrchamp** [comment]
Looks great! Thank you for making this core branding element much more lightweight and streamlined.

**Pull request merged**
