### PR TITLE
brick: Use data URI SVG

### LINKED ISSUE #17: Wishlist: Reduce HTTP Requests to 1
With the rewrite, there are only three HTTP requests being made when showBrick is enabled. So let's pose the question: Can we get down to 1?

- Does main.js need to be separate from ub-php.js?
- Can we use a base64 data URI for the NC State brick instead? (This would match all other images in the utility bar).

I'm very grateful for work that has been done - the new ub-php.js has a noticeable improvement in load time for me - my hope is to continue to reduce the impact of this ubiquitous script. Thank you again for your consideration.

### LINKED ISSUE #26: Update build system
We're using Laravel Mix version 1.7.2. The latest version is 5.0.5. I'm not sure what it would entail, but we need to upgrade. We could also explore other approaches to building that don't rely on Laravel Mix, but I doubt that will prove to be simpler than the upgrade.

### PR DESCRIPTION
**Pull request by jrchamp**
Fixes #17 
Fixes #26

It looks like main.js doesn't exist any more, so if accepted, this will reduce both the number of total network requests and bytes.

I took the .eps from brand.ncsu.edu, passed it through inkscape to get a plain SVG, crunched it down with [SVGOMG](https://jakearchibald.github.io/svgomg/) precision 3 and fixed the red color to #c00 (3384 bytes uncompressed when base64 encoded).

I didn't rebuild the dist file as part of this, so that will need to be added to this before merging.

Please let me know what you think!

### CODE REVIEW

**Comment by apmatthews** [comment]
Looks good to me. I pulled it down and tested locally. I think it makes sense to add the dist file and then look at merging.

I did end up removing main.js in https://github.com/ncstate/utility-bar/commit/c35fd5e0a976a777fa472a6c2c078312c397e7da, for reference.

Something else to consider: https://css-tricks.com/probably-dont-base64-svg/

The other SVGs on this project are base64 so I don't think we _have_ to do the brick differently, but I've used that article's method for the past couple of years with good results.

**Comment by jrchamp** [comment]
Hi @apmatthews 

I used the URL encoding process as described in the article you mentioned on each of the SVGs. The new file is 17.3% smaller than the original (even after adding the brick SVG as a data URI).

I don't know how to build the dist file, so could someone do that piece?

**Comment by apmatthews** [comment]
@jrchamp Awesome! Looks like you were able to get it to build too? I was having some trouble building for production (`npm run production`). I think it's probably due to an [old bug in SVGO](https://github.com/svg/svgo/issues/990). My guess is this wasn't an issue before because there wasn't any true SVG markup in the source, but the new URL encoded SVGs are probably being picked up by SVGO. #26 might be the answer, but I'm curious if you ran into any issues in 2490799.

**Comment by jrchamp** [comment]
I had to tell postcss-svgo to leave it alone since it was already optimized to get it to build. #26 solved the issue for me.

**Comment by jrchamp** [comment]
Do you want me to add the build system update that worked for me to this pull request?

**Comment by apmatthews** [comment]
Yes, please 🙂

**Comment by jrchamp** [comment]
Done.

**Comment by jrchamp** [comment]
It's all building cleanly for me. sass-loader should be current now too. Please let me know if you have any questions.

**Comment by apmatthews** [comment]
I'm able to build now, but seeing this:

Screen Shot 2020-09-01 at 2 56 07 PM

The issue is that whitespace isn't being stripped out of the HTML template during the production build. I think that's what [this line](https://github.com/ncstate/utility-bar/blob/8b2a44b5ab168d915289bbb3668bd371eab98bb7/webpack.mix.js#L25) is supposed to do, but maybe it's not respected in the latest version of the build packages?

**Comment by jrchamp** [comment]
Hmm, I think they moved some of the "option" to "sassOptions".

**Comment by apmatthews** [comment]
I just added the `dist` folder to `.gitignore` to make PRs a little simpler and cleaner. Would you mind merging that in from master and excluding the `dist` updates from this PR?

**Comment by jrchamp** [comment]
Done. I rebased the changes so that it doesn't have the dist file flipping back and forth. It looks like `minimize: true` has removed the extra whitespace characters from the html-loader.

**Comment by apmatthews** [comment]
@jrchamp Thanks for the contribution and for rolling with all the build updates. I've dropped it on the CDN. I'm not entirely sure how long it takes to move through all the pipes, but we should see this update in production sometime today. Thanks again!

**Pull request merged**
