### PR TITLE
Use existing ncstate-utility-bar if available

### PR DESCRIPTION
**Pull request by jrchamp**
- Prevents the loss of the original utility bar node;
- Works correctly when utility bar node is not an immediate child of body

### CODE REVIEW

**Comment by jrchamp** [comment]
Ran into these two problems today: first it was throwing an error because it could not replace the element and when it succeeded, it completely replaced the element (causing a loss of the existing attributes).

@flashadvocate - Hopefully this works with your code?

**Comment by flashadvocate** [comment]
Don't see it being an issue. My refactor just pretties up the enqueueing process, and doesn't touch any of the JS

**Comment by jrchamp** [comment]
Here's a test case showing that the utility bar does not initialize when `#ncstate-utility-bar` is not an immediate child of body: https://rayne.delta.ncsu.edu/test_utility-bar-grandchild.php

**Comment by apmatthews** [comment]
It's been awhile now, but I think both of these behaviors were intentional. Allowing users to place the UB in wrappers and/or apply their own attributes provides a level of flexibility that invites alteration. Controlling the attributes and wrapper of the bar makes it less prone to conflict with other styles and limits the contexts we have to consider when coding.

**Comment by jrchamp** [comment]
If that's the intended behavior, I can accept that. However, the bar should always initialize when the script is included and not accept a node that does not meet the requirements. I'll put something together.

**Pull request closed without merging**
